# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{daemons-mikehale}
  s.version = "1.0.13"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Hale", "Thomas Uehlinger", "Travis Whitton", "Chris Kline"]
  s.date = %q{2010-01-24}
  s.description = %q{        This is Daemons 1.0.10 with the addition of Chris Kline's fix from http://blog.rapleaf.com/dev/?p=19

        Includes ability to change the process uid/gid. Also logdir can be specified seperate from piddir.

        Daemons provides an easy way to wrap existing ruby scripts (for example a self-written server) to be run as a daemon and to be controlled by simple start/stop/restart commands.

        If you want, you can also use daemons to run blocks of ruby code in a daemon process and to control these processes from the main application.

        Besides this basic functionality, daemons offers many advanced features like exception backtracing and logging (in case your ruby script crashes) and monitoring and automatic restarting of your processes if they crash.

        Daemons includes the daemonize.rb script written by Travis Whitton to do the daemonization process.
}
  s.email = %q{th.uehlinger@gmx.ch}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown",
     "TODO"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "Releases",
     "TODO",
     "VERSION",
     "daemons-mikehale.gemspec",
     "examples/call/call.rb",
     "examples/call/call_monitor.rb",
     "examples/daemonize/daemonize.rb",
     "examples/run/ctrl_crash.rb",
     "examples/run/ctrl_exec.rb",
     "examples/run/ctrl_exit.rb",
     "examples/run/ctrl_keep_pid_files.rb",
     "examples/run/ctrl_monitor.rb",
     "examples/run/ctrl_multiple.rb",
     "examples/run/ctrl_normal.rb",
     "examples/run/ctrl_ontop.rb",
     "examples/run/ctrl_optionparser.rb",
     "examples/run/ctrl_proc.rb",
     "examples/run/ctrl_proc.rb.output",
     "examples/run/ctrl_proc_multiple.rb",
     "examples/run/ctrl_proc_multiple.rb.output",
     "examples/run/ctrl_proc_simple.rb",
     "examples/run/myserver.rb",
     "examples/run/myserver_crashing.rb",
     "examples/run/myserver_crashing.rb.output",
     "examples/run/myserver_exiting.rb",
     "lib/daemons.rb",
     "lib/daemons/application.rb",
     "lib/daemons/application_group.rb",
     "lib/daemons/change_privilege.rb",
     "lib/daemons/cmdline.rb",
     "lib/daemons/controller.rb",
     "lib/daemons/daemonize.rb",
     "lib/daemons/etc_extension.rb",
     "lib/daemons/exceptions.rb",
     "lib/daemons/monitor.rb",
     "lib/daemons/pid.rb",
     "lib/daemons/pidfile.rb",
     "lib/daemons/pidmem.rb",
     "setup.rb"
  ]
  s.homepage = %q{http://github.com/technicalpickles/the-perfect-gem}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A toolkit to convert your script to a controllable daemon (with Chris Kline's fix)}
  s.test_files = [
    "examples/call/call.rb",
     "examples/call/call_monitor.rb",
     "examples/daemonize/daemonize.rb",
     "examples/run/ctrl_crash.rb",
     "examples/run/ctrl_exec.rb",
     "examples/run/ctrl_exit.rb",
     "examples/run/ctrl_keep_pid_files.rb",
     "examples/run/ctrl_monitor.rb",
     "examples/run/ctrl_multiple.rb",
     "examples/run/ctrl_normal.rb",
     "examples/run/ctrl_ontop.rb",
     "examples/run/ctrl_optionparser.rb",
     "examples/run/ctrl_proc.rb",
     "examples/run/ctrl_proc_multiple.rb",
     "examples/run/ctrl_proc_simple.rb",
     "examples/run/myserver.rb",
     "examples/run/myserver_crashing.rb",
     "examples/run/myserver_exiting.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

